version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/lambda"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/mcp"
    schedule:
      interval: "weekly"
      day: "monday"
